### PR TITLE
Refactoring proposal for networking implementation

### PR DESCRIPTION
**Pull request by yuzushioh**
Issue/Task Number:  none

# Overview

This Pull Request is a refactoring proposal for `HTTPClient` and its related classes such as `Request`, `RequestBuilder` and `Endpoint` 

# Changes

In this project, there are 6 classes to construct and send HTTPRequests. `ClientConfiguration`, `HTTPClient`, `APIEndpoint`,  `Request`, `RequestBuilder`, and `RequestParameters`. But some of the properties and tasks, which are necessary for http requests, are covered and implemented over multiple places.

 For example there is a property for http header in `Endpoint` (which is responsible for specifying where to send requests), and session task for http request is created in `Request` class using a session defined in `HTTPClient` class.

### Tasks that each class is responsible for

※ I use protocol for interface definitions but it is just for examples in the PR.

#### ClientConfiguration
`ClientConfiguration ` stays the same.

#### Endpoint
`Endpoint` is only responsible only for specifying which endpoint to request and what type of task it is.

The interface looks something like this

```swift
enum Task {

    case requestPlain

    case requestParameters(Parametrable)
}

protocol Endpoint {

    var path: String { get }

    var task: Task { get }
}
```

This property and method in `Endpoint` will be moved to `RequestBuilder`.

```swift

var additionalHeaders: [String: String]?

func makeURL(withBaseURL baseURL: String) -> URL?
```

#### RequestBuilder & Request

`ReqestBuilder` is responsible only for building http requests and adding necessary information such as http headers and body parameters.  It takes `ClientConfiguration` as a parameter. All the logic in building `HTTPRequest` should be implemented here in this class to minimize the dependencies.

`Request` is responsible for building a request with `RequestBuilder` and handling response object mapping it to a model. (`RequestBuilder` and `Request` may be mergeable since `Request` class is just wrapping `RequestBuilder`)

The interface looks something like this

```swift
protocol RequestBuilder {

    func contentTypeHeader() -> String

    func acceptHeader() -> String

    func encodedAuthorizationHeader() throws -> String

    func addRequiredHeaders(toRequest request: inout URLRequest) throws

    func buildHTTPURLRequest(withEndpoint endpoint: APIEndpoint) throws -> URLRequest
}
```
 
By making this change and moving methods originally implemented in `RequestParameters`, `RequestParameters` class will not be necessary anymore.

#### HTTPClient
`HTTPClient` is responsible only for sending HTTPRequests. `session.dataTask` is called in `Request` class for current implementation, but I think it should be called in `HTTPClient`.

Interface looks something like this

```swift
protocol SessionTask: class {

    func resume()

    func cancel()
}

protocol HTTPClient {

    func request<ResultType>(toEndpoint endpoint: APIEndpoint, callback: Request<ResultType>.Callback?) -> SessionTask?
}
```

### Overall 

By applying those changes, each class will have their own tasks in order to execute requests, and also multi-covered tasks and properties which exist right now will be removed , which will make the codebase simpler and easier to read.

# Impact

It should be adapted step by step because the changes will be a bit large and it may be hard to review.

Whether this proposal is accepted or not, It is still possible and better to remove `RequestParameters` and move its tasks to `RequestBuilder`.

### CODE REVIEW

**Comment by mederic-p** [comment]
Hey, thanks a lot for the proposal.
I thought about refactoring the networking logic too. As you said some class are responsible of different task and this should be refactored.
I'd love to see what you can end up with the changes that you proposed. I don't have the time right now to work on it but if you'd like to submit a PR implementing the proposed changes it'd be awesome.
Just a quick note: I think I split out `RequestBuilder` when I added the new `SocketClient` so you may need to make sure that we don't have conflict with this.

**Comment by yuzushioh** [comment]
@mederic-p Thank you for the replay and the quick note. I will implement the changes and submit pull requests.

**Comment by T-Dnzt** [comment]
@yuzushioh Thanks for the proposal! In the future, please create an issue to discuss proposals :)

**Comment by mederic-p** [comment]
#46

**Pull request closed without merging**
